//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.UserInterface.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Araclar
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Yil { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public string SonKM { get; set; }
        public string MotorGucu { get; set; }
        public string Cekis { get; set; }
        public string Kapi { get; set; }
        public string KasaTipi { get; set; }
        public string Renk { get; set; }
        public string HasarDurumu { get; set; }
        public Nullable<bool> KiraDurumu { get; set; }
        public string Plaka { get; set; }
        public byte[] Resim { get; set; }
    }
}
